export function install(){
  const pages=[
    {kicker:'START',title:'투자 사용 설명서',body:`<div class="guide-intro"><div class="guide-book">▤</div><div><h3>기록이 쌓일수록 나에게 맞는 투자 원칙이 보입니다.</h3><p>투자는 장기 스윙과 데이트레이딩을 한 앱에서 분리해 기록하는 로컬 우선 워크스테이션입니다. 상단의 SWING·DAY 스위치로 모드를 전환합니다.</p></div></div><div class="guide-grid"><article><strong>데이터는 내 PC에</strong><p>포지션, 거래와 저널은 로컬 데이터베이스에 저장됩니다.</p></article><article><strong>가격은 종가 기준</strong><p>온라인 갱신은 최근 완료된 미국장 일봉을 사용합니다.</p></article></div>`},
    {kicker:'SWING 1/2',title:'Swing · Today와 계획',body:`<div class="guide-list"><article><b>Today</b><p>Total assets, 투자 가능 금액, 포트폴리오 Heat와 활성 포지션을 요약합니다. US Macro & Event Radar는 최신 경제지표와 향후 7일 주요 일정을 보여줍니다.</p></article><article><b>Trade planner</b><p>Entry·Stop·Target과 계좌 위험률을 입력하면 수량, R:R, 노출 비중을 계산합니다. 전략 관리에서 근거 항목을 추가하거나 숨길 수 있습니다.</p></article><article><b>Import position</b><p>앱 사용 이전부터 보유한 포지션을 등록합니다. 현재가는 온라인 갱신으로 채우며 진입 근거도 함께 보존합니다.</p></article></div>`},
    {kicker:'SWING 2/2',title:'Swing · 운용과 분석',body:`<div class="guide-list"><article><b>Positions · 온라인에서 가져오기</b><p>선택한 공급자의 최근 완료 종가로 보유 포지션과 벤치마크를 갱신합니다. 포지션 관리를 열어 추가매수, 일부 매도, 손절가 변경, 전체 종료를 기록합니다.</p></article><article><b>Journal</b><p>당시 알고 있던 정보와 판단을 남겨 결과에 맞춰 기억을 고치는 일을 방지합니다.</p></article><article><b>Analytics</b><p>자산 변화, 입출금, 전체·벤치마크 수익률, 전략별 승률과 기대값, 매도 후 추적 결과를 분석합니다.</p></article></div>`},
    {kicker:'DAY',title:'Day trading desk',body:`<div class="guide-list"><article><b>Today</b><p>스윙 투자금을 제외한 Day capital, 오늘 손익과 투입금 대비 수익률을 표시합니다. 양피지 버튼으로 거래 저널을 바로 작성합니다.</p></article><article><b>Trade record</b><p>계획이 아닌 완료된 진입가·수량·청산가·수수료·전략을 후향적으로 기록합니다. R 계산은 사용하지 않습니다.</p></article><article><b>Journal & Analytics</b><p>저널을 포스트잇 보드에서 읽고, 0선을 기준으로 일별 손익과 전략별 승률·평균 손익·Profit factor를 비교합니다.</p></article></div>`},
    {kicker:'SETTINGS',title:'버튼과 데이터 관리',body:`<div class="guide-list"><article><b>⚙ 시장 데이터 설정</b><p>기본 yfinance와 선택형 Alpaca 사이를 전환합니다. API 키는 Alpaca를 선택할 때만 필요합니다.</p></article><article><b>▤ 사용 설명서</b><p>이 창을 언제든 다시 엽니다.</p></article><article><b>전략 관리</b><p>사용할 전략을 추가하거나 표시에서 숨깁니다. 이미 거래에 사용된 전략과 과거 통계는 삭제되지 않습니다.</p></article><article><b>백업</b><p>앱을 종료하고 <code>%LOCALAPPDATA%&#92;투자&#92;data&#92;workstation.db</code>를 복사하면 개인 기록을 백업할 수 있습니다.</p></article></div>`}
  ];
  function open(){let index=0;document.querySelector('.guide-modal')?.remove();const modal=document.createElement('div');modal.className='modal-backdrop guide-modal';modal.innerHTML='<div class="modal-panel guide-panel"><div class="modal-head"><div><p class="guide-kicker"></p><h2></h2></div><button class="btn ghost" data-close>닫기</button></div><div class="modal-body guide-body"></div><div class="guide-footer"><div class="guide-dots"></div><div><button class="btn ghost" data-prev>이전</button><button class="btn" data-next>다음</button></div></div></div>';document.body.appendChild(modal);const render=()=>{const page=pages[index];modal.querySelector('.guide-kicker').textContent=page.kicker;modal.querySelector('h2').textContent=page.title;modal.querySelector('.guide-body').innerHTML=page.body;modal.querySelector('.guide-dots').innerHTML=pages.map((_,i)=>`<i class="${i===index?'active':''}"></i>`).join('');modal.querySelector('[data-prev]').disabled=index===0;modal.querySelector('[data-next]').textContent=index===pages.length-1?'완료':'다음'};modal.querySelector('[data-close]').onclick=()=>modal.remove();modal.querySelector('[data-prev]').onclick=()=>{if(index>0){index--;render()}};modal.querySelector('[data-next]').onclick=()=>{if(index===pages.length-1)modal.remove();else{index++;render()}};render()}
  return {open};
}
