const state={view:'today',data:null,journal:[]};const viewOverrides={};
const $=s=>document.querySelector(s);const money=n=>new Intl.NumberFormat('en-US',{minimumFractionDigits:2,maximumFractionDigits:2}).format(Number(n||0));
const api=async(path,options={})=>{const r=await fetch(path,{headers:{'Content-Type':'application/json'},...options});const d=await r.json();if(!r.ok)throw new Error(d.error||'요청에 실패했습니다.');return d};
const toast=msg=>{const el=$('#toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2400)};
function title(name,sub){$('#pageTitle').textContent=name;$('#dateLabel').textContent=sub}
function kpi(label,value,foot,cls=''){return `<div class="card kpi"><div class="kpi-label">${label}</div><div class="kpi-value ${cls}">${value}</div><div class="kpi-foot">${foot}</div></div>`}
function tradesTable(items){if(!items.length)return `<div class="empty"><strong>아직 거래가 없습니다.</strong>Trade Planner에서 첫 계획을 만들어보세요.</div>`;return `<table><thead><tr><th>Ticker</th><th>Status</th><th>Entry</th><th>Stop</th><th>Target</th><th>Risk</th><th>R:R</th></tr></thead><tbody>${items.map(t=>`<tr><td class="ticker">${t.ticker}</td><td><span class="badge ${t.status==='active'?'green':''}">${t.status}</span></td><td class="mono">${money(t.entry)}</td><td class="mono">${money(t.stop)}</td><td class="mono">${money(t.target)}</td><td class="mono">${t.risk_pct.toFixed(1)}%</td><td class="mono">1 : ${t.rr.toFixed(2)}</td></tr>`).join('')}</tbody></table>`}
function today(){const d=state.data,m=d.metrics,s=d.settings;title('Good morning.','Your daily decision desk');$('#content').innerHTML=`<section class="hero"><div><h2>판단은 당신이, 규율과 기억은 시스템이.</h2><p>오늘도 계획된 위험 안에서 가장 좋은 거래만 선택하세요.</p></div><button class="btn" data-go="planner">Plan a trade</button></section><div class="grid kpis">${kpi('Account value',`$${money(s.accountValue)}`,'USD portfolio base')}${kpi('Portfolio heat',`${m.portfolioHeat.toFixed(1)}%`,`Limit ${s.maxPortfolioHeatPct}%`,m.portfolioHeat>s.maxPortfolioHeatPct?'negative':'positive')}${kpi('Active positions',m.activeCount,'Open risk units')}${kpi('Expectancy',`${m.expectancy>=0?'+':''}${m.expectancy.toFixed(2)}R`,`${m.closedCount} closed trades`,m.expectancy>0?'positive':'')}</div><div class="grid two-col"><section class="card"><div class="card-head"><div><h2>Current desk</h2><p class="sub">Active and planned trades</p></div><button class="btn ghost" data-go="positions">View all</button></div>${tradesTable([...d.active,...d.planned].slice(0,6))}</section><aside class="card"><div class="card-head"><div><h2>Quick actions</h2><p class="sub">Keep the workflow moving</p></div></div><div class="quick"><button data-go="planner">Create trade plan <span>→</span></button><button data-go="journal">Write decision note <span>→</span></button><button data-go="analytics">Review performance <span>→</span></button></div><div class="validation" style="margin-top:20px">✓ Local database ready<br><span style="color:var(--muted)">Market data connector is not configured yet.</span></div></aside></div>`;bindGo()}
function planner(){const s=state.data.settings;title('Trade planner','Define the risk before the reward');$('#content').innerHTML=`<div class="grid planner-layout"><section class="card"><div class="card-head"><div><h2>New long plan</h2><p class="sub">The system validates your decision. It does not make it.</p></div></div><form id="tradeForm"><div class="row"><label>Ticker<input name="ticker" placeholder="APH" required></label><label>Setup<select name="setup"><option>Pullback</option><option>Breakout</option><option>AVWAP bounce</option><option>LL → HL reversal</option></select></label></div><label>Trade thesis<textarea name="thesis" placeholder="Why is this trade allowed?"></textarea></label><div class="row three"><label>Entry (USD)<input name="entry" type="number" step="0.01" placeholder="124.50" required></label><label>Stop (USD)<input name="stop" type="number" step="0.01" placeholder="120.70" required></label><label>Target (USD)<input name="target" type="number" step="0.01" placeholder="132.10" required></label></div><div class="row"><label>Account value (USD)<input name="accountValue" type="number" value="${s.accountValue}" required></label><label>Account risk (%)<input name="riskPct" type="number" step="0.1" value="${s.maxTradeRiskPct}" required></label></div><label>Notes<textarea name="notes" placeholder="Market regime, earnings, relative strength, invalidation..."></textarea></label><button class="btn" type="submit">Save trade plan</button></form></section><aside class="card"><div class="card-head"><div><h2>Live risk preview</h2><p class="sub">Calculated from your inputs</p></div></div><div class="result-stack"><div class="result-row"><span>Stop distance</span><strong id="pDistance">—</strong></div><div class="result-row"><span>Risk amount</span><strong id="pRisk">—</strong></div><div class="result-row"><span>Position size</span><strong id="pSize">—</strong></div><div class="result-row"><span>Reward / Risk</span><strong id="pRR">—</strong></div><div class="result-row"><span>Exposure</span><strong id="pExposure">—</strong></div></div><div id="validation" class="validation warn">가격을 입력하면 거래 구조를 검증합니다.</div></aside></div>`;const f=$('#tradeForm');f.addEventListener('input',preview);f.addEventListener('submit',saveTrade);preview()}
function preview(){const f=$('#tradeForm');if(!f)return;const v=Object.fromEntries(new FormData(f)),e=+v.entry,st=+v.stop,t=+v.target,a=+v.accountValue,r=+v.riskPct,dist=e-st,risk=a*r/100,qty=dist>0?Math.floor(risk/dist):0,rr=dist>0?(t-e)/dist:0,exposure=a>0?qty*e/a*100:0;$('#pDistance').textContent=dist>0?`${dist.toFixed(2)} (${(dist/e*100).toFixed(2)}%)`:'—';$('#pRisk').textContent=risk>0?`$${money(risk)}`:'—';$('#pSize').textContent=qty>0?`${money(qty)} shares`:'—';$('#pRR').textContent=rr>0?`1 : ${rr.toFixed(2)}`:'—';$('#pExposure').textContent=exposure>0?`${exposure.toFixed(1)}%`:'—';const val=$('#validation');if(st>0&&e>st&&t>e){val.className='validation';val.textContent=rr>=1.5?'✓ 가격 구조가 유효하며 R:R 기준을 통과합니다.':'✓ 가격 구조는 유효하지만 R:R이 1.5 미만입니다.'}else{val.className='validation warn';val.textContent='Long 거래는 Stop < Entry < Target이어야 합니다.'}}
async function saveTrade(ev){ev.preventDefault();const p=Object.fromEntries(new FormData(ev.target));for(const k of ['entry','stop','target','accountValue','riskPct'])p[k]=+p[k];try{await api('/api/trades',{method:'POST',body:JSON.stringify(p)});await load();toast('거래 계획을 저장했습니다.');switchView('positions')}catch(e){toast(e.message)}}
function positions(){title('Positions','Planned risk and active exposure');const all=[...state.data.active,...state.data.planned,...state.data.recent.filter(x=>x.status==='closed')].filter((x,i,a)=>a.findIndex(y=>y.id===x.id)===i);$('#content').innerHTML=`<div class="grid kpis">${kpi('Active risk',`${state.data.metrics.portfolioHeat.toFixed(1)}%`,`Limit ${state.data.settings.maxPortfolioHeatPct}%`)}${kpi('Planned',state.data.planned.length,'Awaiting execution')}${kpi('Active',state.data.active.length,'Currently exposed')}${kpi('Closed',state.data.metrics.closedCount,'Recorded outcomes')}</div><section class="card"><div class="card-head"><div><h2>Trade ledger</h2><p class="sub">A single source of truth for planned and executed decisions</p></div><button class="btn" data-go="planner">New plan</button></div>${tradesTable(all)}</section>`;bindGo()}
async function loadJournal(){state.journal=await api('/api/journal')}
function journal(){title('Journal','Preserve the decision, not just the result');$('#content').innerHTML=`<div class="grid two-col"><section class="card"><div class="card-head"><div><h2>Decision notes</h2><p class="sub">What did you know at the time?</p></div></div><div class="journal-list">${state.journal.length?state.journal.map(j=>`<article class="journal-item"><time>${new Date(j.created_at).toLocaleString('ko-KR')}</time><h3>${j.title}</h3><p>${j.body||'내용 없음'}</p></article>`).join(''):'<div class="empty"><strong>기록된 노트가 없습니다.</strong>첫 의사결정의 맥락을 남겨보세요.</div>'}</div></section><aside class="card"><div class="card-head"><div><h2>New note</h2><p class="sub">A 30-second record is enough.</p></div></div><form id="journalForm"><label>Title<input name="title" placeholder="Pre-market note" required></label><label>State<select name="mood"><option>Neutral</option><option>Focused</option><option>Confident</option><option>Anxious</option><option>FOMO</option></select></label><label>Decision context<textarea name="body" placeholder="What do I see, expect, and risk?"></textarea></label><button class="btn" type="submit">Save note</button></form></aside></div>`;$('#journalForm').addEventListener('submit',async e=>{e.preventDefault();try{await api('/api/journal',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});await loadJournal();toast('의사결정 노트를 저장했습니다.');journal()}catch(err){toast(err.message)}})}
function analytics(){const m=state.data.metrics;title('Analytics','Turn experience into evidence');$('#content').innerHTML=`<div class="grid kpis">${kpi('Closed trades',m.closedCount,'Sample size')}${kpi('Win rate',`${m.winRate.toFixed(1)}%`,'Outcome frequency')}${kpi('Expectancy',`${m.expectancy>=0?'+':''}${m.expectancy.toFixed(2)}R`,'Average per trade',m.expectancy>0?'positive':'')}${kpi('Data quality',m.closedCount>=30?'Ready':'Building',m.closedCount>=30?'Enough for early review':`${30-m.closedCount} trades to first review`)}</div><div class="grid two-col"><section class="card"><div class="card-head"><div><h2>Evidence engine</h2><p class="sub">Metrics unlock as your journal grows</p></div></div><div class="result-stack"><div class="result-row"><span>Setup expectancy</span><strong>${m.closedCount?'Collecting':'Locked'}</strong></div><div class="result-row"><span>MAE / MFE</span><strong>Next phase</strong></div><div class="result-row"><span>Exit efficiency</span><strong>Next phase</strong></div><div class="result-row"><span>Market regime performance</span><strong>Next phase</strong></div></div></section><aside class="card"><h2>Statistical honesty</h2><p class="sub" style="line-height:1.8;margin-top:12px">결과를 서둘러 일반화하지 않습니다. 충분한 표본이 쌓이기 전에는 수치를 성과가 아닌 관찰로 표시합니다.</p><div class="bar"><span style="width:${Math.min(100,m.closedCount/30*100)}%"></span></div><p class="sub">${m.closedCount} / 30 closed trades</p></aside></div>`}
function bindGo(){document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>switchView(b.dataset.go))}
function switchView(view){state.view=view;document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===view));(viewOverrides[view]||({today,planner,positions,journal,analytics}[view]))()}
async function load(){state.data=await api('/api/dashboard');await loadJournal()}
document.querySelectorAll('.nav-item').forEach(b=>b.onclick=()=>switchView(b.dataset.view));
const date=new Intl.DateTimeFormat('en-US',{weekday:'long',month:'long',day:'numeric'}).format(new Date());$('#dateLabel').textContent=date;
const heartbeat=()=>fetch('/api/heartbeat',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'}).catch(()=>{});heartbeat();setInterval(heartbeat,2000);

await import('/features.js').then(module=>module.install({state,viewOverrides,$,api,money,toast,title,kpi,tradesTable,bindGo,load,preview,switchView}));
await import('/exit-review.js');
await import('/final-layout.js').then(module=>module.install({state,viewOverrides,$,api,money,toast,title,kpi,tradesTable,bindGo,load,switchView}));
await import('/cashflow-ui.js').then(module=>module.install({state,viewOverrides,$,api,money,toast,title,kpi,load}));
await import('/portfolio-overview.js').then(module=>module.install({viewOverrides,$,api,money}));
await import('/trade-lifecycle.js').then(module=>module.install({state,viewOverrides,$,api,money,toast,load}));
await import('/sector-benchmarks.js').then(module=>module.install({viewOverrides,$,api}));
await import('/exit-quality.js').then(module=>module.install({viewOverrides,$,api,money,toast}));
await import('/position-management.js').then(module=>module.install({state,viewOverrides,$,api,money,toast,load}));
await import('/strategy-manager.js').then(module=>module.install({state,viewOverrides,api,load,toast}));
await import('/macro-news.js').then(module=>module.install({viewOverrides,api}));
await import('/day-mode.js').then(module=>module.install({state,api,load,toast,title,money,switchView}));
const providerSetup=await import('/provider-setup.js').then(module=>module.install({api,toast}));
const appGuide=await import('/app-guide.js').then(module=>module.install());
document.querySelector('.avatar').onclick=()=>providerSetup.open(true);
document.querySelector('.guide-button').onclick=()=>appGuide.open();
async function bootstrap(){
  await load();switchView('today');
  const provider=await providerSetup.status();
  if(!provider.configured){console.warn('Selected market data provider is not configured.')}
  const initialView=state.view;
  try{
    await api('/api/positions/refresh-prices',{method:'POST',body:'{}'});
    await load();
    if(!document.body.classList.contains('day-mode')&&state.view===initialView)switchView(initialView);
  }catch(error){console.warn('Automatic close refresh failed:',error.message)}
}
bootstrap().catch(e=>{$('#content').innerHTML=`<div class="empty"><strong>앱을 불러오지 못했습니다.</strong>${e.message}</div>`});
