let catalog={
  '차트 구조':['핵심: LL 이후 상승 Swing AVWAP 교점','평행 패턴 저점','평행 패턴 돌파 후 Test·재상승','대칭삼각','상승삼각','하강삼각','하모닉 패턴','상승 패턴','지지·저항 전환 후 Retest','박스권 저항 돌파','HH·HL 상승 구조'],
  '모멘텀':['RSI 지지','스토캐스틱 골든크로스','스토캐스틱 상승'],
  '자금 흐름':['CMF 상승','CMF 0선 상향 돌파','가격 LL·CMF HL 양의 다이버전스','Accumulation/Distribution 상승'],
  '추세·변동성':['상승 이동평균선 Pullback 지지','거래량 동반 Breakout','ATR 변동성 Breakout','52주 신고가 Breakout'],
  '상대강도':['QQQ 대비 상대강도 상승','SPY 대비 상대강도 상승','섹터 ETF 대비 상대강도 상승'],
  '진입 확인':['저점 반전 확인','직전 고점 돌파','거래량 증가','지지선 재확인','Bullish Engulfing 확인']
};

function evidenceBuilder(){return Object.entries(catalog).map(([group,items])=>`<div class="evidence-group"><h3>${group}</h3><div class="chip-grid">${items.map(item=>`<label class="evidence-chip"><input type="checkbox" name="evidence" data-group="${group}" value="${item}"><span>${item}</span></label>`).join('')}</div></div>`).join('')}
function syncCatalog(rows){if(!rows)return;const next={};rows.filter(row=>row.mode==='swing'&&row.active).forEach(row=>(next[row.group_name]??=[]).push(row.label));if(Object.keys(next).length)catalog=next}
function collectEvidence(form){const result={};form.querySelectorAll('input[name="evidence"]:checked').forEach(input=>{(result[input.dataset.group]??=[]).push(input.value)});return result}
function updateConfluence(form){const checked=[...form.querySelectorAll('input[name="evidence"]:checked')],groups=new Set(checked.map(x=>x.dataset.group));form.querySelector('[data-confluence-count]').textContent=`${groups.size}개 영역 · ${checked.length}개 근거`}

export function install(ctx){
  const {state,viewOverrides,$,api,money,toast,title,kpi,tradesTable,bindGo,load,preview,switchView}=ctx;
  queueMicrotask(()=>{
    const basePositions=viewOverrides.positions;
    viewOverrides.positions=()=>{
      basePositions();
      const form=$('#positionForm');
      form.querySelector('button[type="submit"]').insertAdjacentHTML('beforebegin',`<div style="display:grid;gap:14px;margin:4px 0 16px"><div><h2 style="margin:0">진입 전략과 근거</h2><p class="sub">과거 포지션도 동일한 분류로 저장해 향후 성과를 비교합니다.</p></div>${evidenceBuilder()}<div class="confluence-summary"><span>근거 중복</span><strong data-confluence-count>0개 영역 · 0개 근거</strong></div></div>`);
      form.addEventListener('input',()=>updateConfluence(form));
      form.addEventListener('submit',async event=>{
        event.preventDefault();event.stopImmediatePropagation();
        const payload=Object.fromEntries(new FormData(form));
        for(const key of ['quantity','averagePrice','currentPrice'])payload[key]=+payload[key];
        payload.evidence=collectEvidence(form);
        try{await api('/api/positions',{method:'POST',body:JSON.stringify(payload)});await load();toast('기존 포지션과 전략을 저장했습니다.');viewOverrides.positions()}catch(error){toast(error.message)}
      },true);
      const strategyCards=state.data.positions.map(position=>{let evidence={};try{evidence=JSON.parse(position.evidence_json||'{}')}catch{}const tags=Object.values(evidence).flat();return `<article class="journal-item"><div style="display:flex;justify-content:space-between;gap:14px;align-items:center"><div><h3>${position.ticker} · 전략 추적</h3><p>${tags.length?tags.join(' · '):'등록된 전략 근거 없음'}</p></div><button class="btn ghost close-position" data-position-id="${position.id}" data-ticker="${position.ticker}" data-price="${position.current_price}">포지션 종료 기록</button></div></article>`}).join('');
      $('#content').insertAdjacentHTML('beforeend',`<section class="card" style="margin-top:18px"><div class="card-head"><div><h2>전략 추적</h2><p class="sub">청산 결과를 기록하면 전략별 승률과 평균 수익률에 반영됩니다.</p></div></div><div class="journal-list">${strategyCards||'<div class="empty"><strong>추적 중인 전략이 없습니다.</strong></div>'}</div></section><section class="card" style="margin-top:18px"><div class="card-head"><div><h2>Benchmark relative performance</h2><p class="sub">각 포지션의 진입일부터 현재까지 QQQ·SPY 등과 초과수익률을 비교합니다.</p></div></div><div class="row" style="grid-template-columns:1fr auto;margin-bottom:16px"><label>비교 대상 티커<input id="benchmarkTickers" value="QQQ, SPY" placeholder="QQQ, SPY, IWM"></label><button class="btn" id="benchmarkRun">수익률 비교</button></div><div id="benchmarkResults" class="empty"><strong>비교 대상을 실행하세요.</strong>인터넷 연결을 사용해 시장 가격을 불러옵니다.</div></section>`);
      document.querySelectorAll('.close-position').forEach(button=>button.onclick=async()=>{const raw=window.prompt(`${button.dataset.ticker} 청산가(USD)를 입력하세요.`,button.dataset.price);if(raw===null)return;const exitPrice=Number(raw);if(!Number.isFinite(exitPrice)||exitPrice<=0){toast('올바른 청산가를 입력하세요.');return}try{await api(`/api/positions/${button.dataset.positionId}`,{method:'PATCH',body:JSON.stringify({status:'closed',exitPrice})});await load();toast('포지션 결과와 전략 성과를 기록했습니다.');viewOverrides.positions()}catch(error){toast(error.message)}});
      $('#benchmarkRun').onclick=async()=>{
        const output=$('#benchmarkResults'),symbols=$('#benchmarkTickers').value;
        output.className='empty';output.innerHTML='<strong>시장 데이터를 불러오는 중...</strong>';
        try{
          const result=await api(`/api/relative-performance?benchmarks=${encodeURIComponent(symbols)}`);
          if(!result.comparisons.length){output.innerHTML='<strong>비교할 포지션이 없습니다.</strong>기존 포지션을 먼저 등록하세요.';return}
          output.className='';
          output.innerHTML=`<table><thead><tr><th>Position</th><th>Since</th><th>Return</th>${result.benchmarks.map(x=>`<th>${x} / Alpha</th>`).join('')}</tr></thead><tbody>${result.comparisons.map(row=>`<tr><td class="ticker">${row.ticker}</td><td class="mono">${row.openedAt}</td><td class="mono ${row.positionReturnPct>=0?'positive':'negative'}">${row.positionReturnPct>=0?'+':''}${row.positionReturnPct.toFixed(2)}%</td>${row.benchmarks.map(b=>b.error?`<td class="negative">불러오기 실패</td>`:`<td class="mono">${b.returnPct>=0?'+':''}${b.returnPct.toFixed(2)}% / <span class="${b.alphaPct>=0?'positive':'negative'}">${b.alphaPct>=0?'+':''}${b.alphaPct.toFixed(2)}%p</span></td>`).join('')}</tr>`).join('')}</tbody></table><p class="sub" style="margin-top:12px">Alpha = 포지션 수익률 − Benchmark 수익률 · 가격 출처: Yahoo Finance</p>`;
        }catch(error){output.innerHTML=`<strong>시장 데이터를 불러오지 못했습니다.</strong>${error.message}`}
      };
    };
    const baseAnalytics=viewOverrides.analytics;
    viewOverrides.analytics=()=>{
      baseAnalytics();
      const stats=state.data.strategyStats||[];
      $('#content').insertAdjacentHTML('beforeend',`<section class="card" style="margin-top:18px"><div class="card-head"><div><h2>전략별 성과</h2><p class="sub">기존 포지션을 포함해 청산된 결과만 집계합니다.</p></div></div>${stats.length?`<table><thead><tr><th>Category</th><th>Strategy evidence</th><th>Trades</th><th>Win rate</th><th>Avg return</th></tr></thead><tbody>${stats.map(row=>`<tr><td><span class="badge">${row.group}</span></td><td>${row.strategy}</td><td class="mono">${row.trades}</td><td class="mono">${row.winRate.toFixed(1)}%</td><td class="mono ${row.averageReturnPct>=0?'positive':'negative'}">${row.averageReturnPct>=0?'+':''}${row.averageReturnPct.toFixed(2)}%</td></tr>`).join('')}</tbody></table>`:'<div class="empty"><strong>아직 청산된 전략 표본이 없습니다.</strong>Positions에서 포지션 종료를 기록하면 자동 집계됩니다.</div>'}</section>`);
    };
  });

  viewOverrides.planner=()=>{const s=state.data.settings;title('Trade planner','근거를 조립하고 위험을 먼저 정의하세요');$('#content').innerHTML=`<div class="grid planner-layout"><section class="card"><div class="card-head"><div><h2>새 Long 거래 계획</h2><p class="sub">단일 전략명이 아니라 서로 다른 영역의 근거를 중첩합니다.</p></div></div><form id="tradeForm"><div class="row"><label>Ticker<input name="ticker" placeholder="APH" required></label><label>거래 상태<select name="status"><option value="planned">계획</option><option value="active">즉시 활성 포지션</option></select></label></div><label>투자 논지<textarea name="thesis" placeholder="왜 지금 이 거래가 허용되는가?"></textarea></label>${evidenceBuilder()}<div class="confluence-summary"><span>근거 중복</span><strong data-confluence-count>0개 영역 · 0개 근거</strong></div><div class="row three"><label>Entry (USD)<input name="entry" type="number" step="0.01" required></label><label>Stop (USD)<input name="stop" type="number" step="0.01" required></label><label>Target (USD)<input name="target" type="number" step="0.01" required></label></div><div class="row"><label>Account value (USD)<input name="accountValue" type="number" value="${s.accountValue}" required></label><label>Account risk (%)<input name="riskPct" type="number" step="0.1" value="${s.maxTradeRiskPct}" required></label></div><label>메모<textarea name="notes" placeholder="시장 환경, 무효화 조건, 실적 일정 등"></textarea></label><button class="btn" type="submit">거래 계획 저장</button></form></section><aside class="card"><div class="card-head"><div><h2>위험 미리보기</h2><p class="sub">입력값을 기반으로 실시간 계산</p></div></div><div class="result-stack"><div class="result-row"><span>Stop distance</span><strong id="pDistance">—</strong></div><div class="result-row"><span>Risk amount</span><strong id="pRisk">—</strong></div><div class="result-row"><span>Position size</span><strong id="pSize">—</strong></div><div class="result-row"><span>Reward / Risk</span><strong id="pRR">—</strong></div><div class="result-row"><span>Exposure</span><strong id="pExposure">—</strong></div></div><div id="validation" class="validation warn">가격을 입력하면 거래 구조를 검증합니다.</div></aside></div>`;const form=$('#tradeForm');form.addEventListener('input',()=>{preview();updateConfluence(form)});form.addEventListener('submit',async ev=>{ev.preventDefault();const p=Object.fromEntries(new FormData(form));for(const key of ['entry','stop','target','accountValue','riskPct'])p[key]=+p[key];p.setup='근거 중복';p.evidence=collectEvidence(form);try{await api('/api/trades',{method:'POST',body:JSON.stringify(p)});await load();toast('거래 계획을 저장했습니다.');switchView('positions')}catch(error){toast(error.message)}});preview()};

  const positionRows=items=>{if(!items.length)return '<div class="empty"><strong>등록된 보유 포지션이 없습니다.</strong>기존 투자 포지션을 위 양식에서 추가하세요.</div>';return `<table><thead><tr><th>Ticker</th><th>Opened</th><th>Avg price</th><th>Current</th><th>Quantity</th><th>Market value</th><th>Unrealized</th></tr></thead><tbody>${items.map(p=>{const pnl=(p.current_price-p.average_price)*p.quantity,pct=(p.current_price/p.average_price-1)*100;return `<tr><td class="ticker">${p.ticker}</td><td class="mono">${p.opened_at}</td><td class="mono">$${money(p.average_price)}</td><td class="mono">$${money(p.current_price)}</td><td class="mono">${money(p.quantity)}</td><td class="mono">$${money(p.current_price*p.quantity)}</td><td class="pnl ${pnl>=0?'positive':'negative'}">${pnl>=0?'+':''}$${money(pnl)} (${pct.toFixed(1)}%)</td></tr>`}).join('')}</tbody></table>`};
  viewOverrides.positions=()=>{const d=state.data,m=d.metrics;title('Positions','기존 보유분과 새 거래를 한곳에서 관리합니다');$('#content').innerHTML=`<div class="grid kpis">${kpi('Position value',`$${money(m.positionValue)}`,'Manual holdings')}${kpi('Unrealized P&L',`${m.unrealizedPnl>=0?'+':''}$${money(m.unrealizedPnl)}`,'Entered current prices',m.unrealizedPnl>=0?'positive':'negative')}${kpi('Portfolio heat',`${m.portfolioHeat.toFixed(1)}%`,'Planned stop risk')}${kpi('Holdings',d.positions.length,'Imported manually')}</div><section class="card"><div class="card-head"><div><h2>기존 포지션 등록</h2><p class="sub">Investment Beta 사용 이전에 진입한 보유분을 직접 추가합니다.</p></div></div><form id="positionForm" class="position-form"><div class="row three"><label>Ticker<input name="ticker" required placeholder="NVDA"></label><label>최초 진입일<input name="openedAt" type="date" required></label><label>보유 수량<input name="quantity" type="number" step="0.0001" required></label></div><div class="row three"><label>평균 매수가 (USD)<input name="averagePrice" type="number" step="0.01" required></label><label>현재가 (USD)<input name="currentPrice" type="number" step="0.01" required><span class="field-help">현재는 수동 입력</span></label><label>메모<input name="notes" placeholder="기존 보유분"></label></div><button class="btn" type="submit">기존 포지션 추가</button></form><div class="card-head"><div><h2>보유 포지션</h2><p class="sub">현재가를 기준으로 평가손익을 계산합니다.</p></div></div>${positionRows(d.positions)}</section><section class="card" style="margin-top:18px"><div class="card-head"><div><h2>계획 및 시스템 거래</h2><p class="sub">Trade Planner에서 생성한 거래</p></div><button class="btn" data-go="planner">새 계획</button></div>${tradesTable([...d.active,...d.planned])}</section>`;bindGo();const form=$('#positionForm');form.elements.openedAt.value=new Date().toISOString().slice(0,10);form.addEventListener('submit',async ev=>{ev.preventDefault();const p=Object.fromEntries(new FormData(form));for(const key of ['quantity','averagePrice','currentPrice'])p[key]=+p[key];try{await api('/api/positions',{method:'POST',body:JSON.stringify(p)});await load();toast('기존 포지션을 추가했습니다.');viewOverrides.positions()}catch(error){toast(error.message)}})};

  const equityChart=points=>{if(!points.length)return '<div class="empty"><strong>아직 자산 기록이 없습니다.</strong>현재 총자산을 첫 기준점으로 저장하세요.</div>';const w=760,h=220,pad=28,values=points.map(p=>+p.value),min=Math.min(...values),max=Math.max(...values),range=max-min||Math.max(max*.02,1);const coords=points.map((p,i)=>({x:pad+(points.length===1?.5:i/(points.length-1))*(w-pad*2),y:pad+(max-+p.value)/range*(h-pad*2),...p})),line=coords.map(p=>`${p.x},${p.y}`).join(' '),area=`${pad},${h-pad} ${line} ${w-pad},${h-pad}`;return `<div class="chart-wrap"><svg class="equity-chart" viewBox="0 0 ${w} ${h}" preserveAspectRatio="none"><defs><linearGradient id="equityGradient" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#b7f46b" stop-opacity=".22"/><stop offset="1" stop-color="#b7f46b" stop-opacity="0"/></linearGradient></defs><line class="chart-grid" x1="${pad}" y1="${pad}" x2="${w-pad}" y2="${pad}"/><line class="chart-grid" x1="${pad}" y1="${h-pad}" x2="${w-pad}" y2="${h-pad}"/><polygon class="chart-area" points="${area}"/><polyline class="chart-line" points="${line}"/>${coords.map(p=>`<circle class="chart-dot" cx="${p.x}" cy="${p.y}" r="4"><title>${p.recorded_at}: $${money(p.value)}</title></circle>`).join('')}<text class="chart-label" x="${pad}" y="14">$${money(max)}</text><text class="chart-label" x="${pad}" y="${h-4}">$${money(min)}</text></svg></div>`};
  viewOverrides.analytics=()=>{const d=state.data,m=d.metrics,shots=d.snapshots,start=shots[0]?.value||0,last=shots.at(-1)?.value||0,change=start?((last/start-1)*100):0;title('Analytics','자산 변화와 거래 품질을 함께 측정합니다');$('#content').innerHTML=`<div class="grid kpis">${kpi('Current assets',`$${money(last||d.settings.accountValue)}`,'Latest snapshot')}${kpi('Asset change',`${change>=0?'+':''}${change.toFixed(2)}%`,'Since first snapshot',change>=0?'positive':'negative')}${kpi('Win rate',`${m.winRate.toFixed(1)}%`,`${m.closedCount} closed trades`)}${kpi('Expectancy',`${m.expectancy>=0?'+':''}${m.expectancy.toFixed(2)}R`,'Average per trade',m.expectancy>0?'positive':'')}</div><section class="card"><div class="card-head"><div><h2>자산 변화</h2><p class="sub">입출금이 포함된 총자산 스냅샷입니다.</p></div></div>${equityChart(shots)}<form id="snapshotForm" class="snapshot-row" style="margin-top:18px"><label>기록일<input name="recordedAt" type="date" required></label><label>총자산 (USD)<input name="value" type="number" step="0.01" value="${last||d.settings.accountValue}" required></label><label>메모<input name="note" placeholder="월말 결산, 입금 포함 등"></label><button class="btn" type="submit">자산 기록</button></form></section><div class="grid two-col" style="margin-top:18px"><section class="card"><h2>거래 분석</h2><div class="mini-stat"><span>표본 수</span><strong>${m.closedCount} trades</strong></div><div class="mini-stat"><span>Expectancy</span><strong>${m.expectancy.toFixed(2)}R</strong></div><div class="mini-stat"><span>Setup 분석</span><strong>${m.closedCount>=30?'검토 가능':'데이터 축적 중'}</strong></div></section><aside class="card"><h2>측정 원칙</h2><p class="sub" style="line-height:1.8;margin-top:12px">총자산 그래프에는 입출금 영향이 섞일 수 있습니다. 향후 거래수익과 현금 흐름을 분리해 성과를 계산합니다.</p></aside></div>`;const form=$('#snapshotForm');form.elements.recordedAt.value=new Date().toISOString().slice(0,10);form.addEventListener('submit',async ev=>{ev.preventDefault();const p=Object.fromEntries(new FormData(form));p.value=+p.value;try{await api('/api/snapshots',{method:'POST',body:JSON.stringify(p)});await load();toast('자산 스냅샷을 저장했습니다.');viewOverrides.analytics()}catch(error){toast(error.message)}})};
}
