let catalog={
  '차트 구조':['핵심: LL 이후 상승 Swing AVWAP 교점','평행 패턴 저점','평행 패턴 돌파 후 Test·재상승','대칭삼각','상승삼각','하강삼각','하모닉 패턴','상승 패턴','지지·저항 전환 후 Retest','박스권 저항 돌파','HH·HL 상승 구조'],
  '모멘텀':['RSI 지지','스토캐스틱 골든크로스','스토캐스틱 상승'],
  '자금 흐름':['CMF 상승','CMF 0선 상향 돌파','가격 LL·CMF HL 양의 다이버전스','Accumulation/Distribution 상승'],
  '추세·변동성':['상승 이동평균선 Pullback 지지','거래량 동반 Breakout','ATR 변동성 Breakout','52주 신고가 Breakout'],
  '상대강도':['QQQ 대비 상대강도 상승','SPY 대비 상대강도 상승','섹터 ETF 대비 상대강도 상승'],
  '진입 확인':['저점 반전 확인','직전 고점 돌파','거래량 증가','지지선 재확인','Bullish Engulfing 확인']
};
const evidenceBuilder=()=>Object.entries(catalog).map(([group,items])=>`<div class="evidence-group"><h3>${group}</h3><div class="chip-grid">${items.map(item=>`<label class="evidence-chip"><input type="checkbox" name="evidence" data-group="${group}" value="${item}"><span>${item}</span></label>`).join('')}</div></div>`).join('');
const collectEvidence=form=>{const result={};form.querySelectorAll('input[name="evidence"]:checked').forEach(input=>(result[input.dataset.group]??=[]).push(input.value));return result};
const updateCount=form=>{const selected=[...form.querySelectorAll('input[name="evidence"]:checked')],groups=new Set(selected.map(x=>x.dataset.group));form.querySelector('[data-confluence-count]').textContent=`${groups.size}개 영역 · ${selected.length}개 근거`};
const syncCatalog=rows=>{if(!rows)return;const next={};rows.filter(row=>row.mode==='swing'&&row.active).forEach(row=>(next[row.group_name]??=[]).push(row.label));if(Object.keys(next).length)catalog=next};

export function install(ctx){
  const {state,viewOverrides,$,api,money,toast,title,kpi,tradesTable,bindGo,load,switchView}=ctx;

  viewOverrides.importPosition=()=>{
    syncCatalog(state.data.strategies);
    title('Import position','프로그램 이전의 보유분을 독립적으로 가져옵니다');
    $('#content').innerHTML=`<div class="grid planner-layout"><section class="card"><div class="card-head"><div><h2>기존 포지션 등록</h2><p class="sub">등록 시 최근 완료된 미국장 종가를 온라인에서 자동으로 가져옵니다.</p></div></div><form id="importForm"><div class="row three"><label>Ticker<input name="ticker" required placeholder="NVDA"></label><label>최초 진입일<input name="openedAt" type="date" required></label><label>보유 수량<input name="quantity" type="number" step="0.0001" required></label></div><label>평균 매수가 (USD)<input name="averagePrice" type="number" step="0.01" required></label><label>투자 논지<textarea name="notes" placeholder="당시 어떤 판단으로 진입했는가?"></textarea></label><div style="display:grid;gap:14px"><div><h2 style="margin:0">진입 전략과 근거</h2><p class="sub">기억나는 범위에서 당시 실제 근거만 선택하세요.</p></div>${evidenceBuilder()}<div class="confluence-summary"><span>근거 중복</span><strong data-confluence-count>0개 영역 · 0개 근거</strong></div></div><button class="btn" type="submit">포지션 가져오기</button></form></section><aside class="card"><div class="card-head"><div><h2>기록 원칙</h2><p class="sub">과거 판단을 현재 정보로 미화하지 않습니다.</p></div></div><div class="result-stack"><div class="result-row"><span>Entry source</span><strong>Manual</strong></div><div class="result-row"><span>Current price</span><strong>Latest daily close</strong></div><div class="result-row"><span>Currency</span><strong>USD</strong></div></div><div class="validation">온라인 조회가 실패하면 평균 매수가로 임시 등록되며 Positions에서 다시 갱신할 수 있습니다.</div></aside></div>`;
    const form=$('#importForm');form.elements.openedAt.value=new Date().toISOString().slice(0,10);form.addEventListener('input',()=>updateCount(form));form.addEventListener('submit',async event=>{event.preventDefault();const payload=Object.fromEntries(new FormData(form));for(const key of ['quantity','averagePrice'])payload[key]=+payload[key];payload.evidence=collectEvidence(form);try{const saved=await api('/api/positions',{method:'POST',body:JSON.stringify(payload)});await load();toast(saved.price_as_of?'최근 종가와 함께 포지션을 가져왔습니다.':'포지션을 등록했습니다. 온라인 종가는 Positions에서 다시 갱신하세요.');switchView('positions')}catch(error){toast(error.message)}});
  };

  const rows=items=>items.length?`<table><thead><tr><th>Ticker</th><th>Opened</th><th>Avg price</th><th>Latest close</th><th>As of</th><th>Quantity</th><th>Market value</th><th>Unrealized</th></tr></thead><tbody>${items.map(p=>{const pnl=(p.current_price-p.average_price)*p.quantity,pct=(p.current_price/p.average_price-1)*100;return `<tr><td class="ticker">${p.ticker}</td><td class="mono">${p.opened_at}</td><td class="mono">$${money(p.average_price)}</td><td class="mono">$${money(p.current_price)}</td><td class="mono">${p.price_as_of||'수동 입력'}</td><td class="mono">${money(p.quantity)}</td><td class="mono">$${money(p.current_price*p.quantity)}</td><td class="mono ${pnl>=0?'positive':'negative'}">${pnl>=0?'+':''}$${money(pnl)} (${pct.toFixed(2)}%)</td></tr>`}).join('')}</tbody></table>`:'<div class="empty"><strong>보유 포지션이 없습니다.</strong>Import position에서 기존 보유분을 가져오거나 Trade planner에서 새 거래를 계획하세요.</div>';

  const renderBenchmarks=()=>`<section class="card" style="margin-top:18px"><div class="card-head"><div><h2>Benchmark relative performance</h2><p class="sub">각 포지션의 진입일부터 QQQ·SPY 등과 초과수익률을 비교합니다.</p></div></div><div class="row" style="grid-template-columns:1fr auto;margin-bottom:16px"><label>비교 대상 티커<input id="benchmarkTickers" value="QQQ, SPY" placeholder="QQQ, SPY, IWM"></label><button class="btn" id="benchmarkRun">수익률 비교</button></div><div id="benchmarkResults" class="empty"><strong>비교 대상을 실행하세요.</strong>인터넷 연결을 사용해 시장 가격을 불러옵니다.</div></section>`;

  viewOverrides.today=()=>{
    const d=state.data,m=d.metrics,s=d.settings;
    const ytd=m.ytdReturnPct===null?'계산 대기':`${m.ytdReturnPct>=0?'+':''}${m.ytdReturnPct.toFixed(2)}%`;
    const goalText=m.goalStatus==='reached'?'목표 달성':m.goalStatus==='estimated'?`약 ${m.goalYears.toFixed(1)}년`:'계산 대기';
    const goalFoot=m.goalStatus==='estimated'?`YTD 연환산 ${m.annualizedReturnPct.toFixed(2)}% 가정`:'30일 이상의 자산 기록과 양의 수익률 필요';
    const holdings=d.positions.map(p=>{const pct=(p.current_price/p.average_price-1)*100;return `<tr><td class="ticker">${p.ticker}</td><td><span class="badge green">IMPORTED HOLDING</span></td><td><span class="badge green">active</span></td><td class="mono">$${money(p.average_price)} → $${money(p.current_price)}</td><td class="mono ${pct>=0?'positive':'negative'}">${pct>=0?'+':''}${pct.toFixed(2)}%</td></tr>`});
    const system=[...d.active,...d.planned].map(t=>`<tr><td class="ticker">${t.ticker}</td><td><span class="badge">${t.status==='active'?'ACTIVE TRADE':'PLANNED'}</span></td><td><span class="badge ${t.status==='active'?'green':''}">${t.status}</span></td><td class="mono">Entry $${money(t.entry)}</td><td class="mono">R:R 1 : ${t.rr.toFixed(2)}</td></tr>`);
    const desk=[...holdings,...system];
    title('Good morning.','Your daily decision desk');
    $('#content').innerHTML=`<section class="hero"><div><h2>판단은 당신이, 규율과 기억은 시스템이.</h2><p>오늘도 계획된 위험 안에서 가장 좋은 거래만 선택하세요.</p></div><button class="btn" data-go="planner">Plan a trade</button></section><div class="grid kpis">${kpi('Total assets',`$${money(m.currentAssets)}`,'Latest asset ledger balance')}${kpi('Active positions',m.activeCount,`Imported ${m.importedActiveCount} · Planner ${m.plannerActiveCount}`)}${kpi('YTD return',ytd,'Net deposits and withdrawals excluded',m.ytdReturnPct>0?'positive':m.ytdReturnPct<0?'negative':'')}${kpi('Goal forecast',goalText,`Goal $${money(s.goalValue)} · ${goalFoot}`,m.goalStatus==='reached'?'positive':'')}</div><div class="grid two-col"><section class="card"><div class="card-head"><div><h2>Current desk</h2><p class="sub">Imported holdings, active trades and plans</p></div><button class="btn ghost" data-go="positions">View all</button></div>${desk.length?`<table><thead><tr><th>Ticker</th><th>Kind</th><th>Status</th><th>Price / Entry</th><th>Return / Plan</th></tr></thead><tbody>${desk.slice(0,8).join('')}</tbody></table>`:'<div class="empty"><strong>관리할 포지션이나 계획이 없습니다.</strong>Import position 또는 Trade planner에서 추가하세요.</div>'}</section><aside class="card"><div class="card-head"><div><h2>자산 목표</h2><p class="sub">목표 금액을 USD로 직접 설정합니다.</p></div></div><form id="goalForm"><label>Goal amount (USD)<input name="goalValue" type="number" min="0.01" step="0.01" value="${s.goalValue}" required></label><button class="btn" type="submit">목표 저장</button></form><div class="validation" style="margin-top:16px">예상 기간은 입출금을 제외한 YTD 성과를 연환산한 시나리오이며 보장 수익률이 아닙니다.</div><div class="quick" style="margin-top:16px"><button data-go="journal">Write decision note <span>→</span></button><button data-go="analytics">Review trading quality <span>→</span></button></div></aside></div>`;
    bindGo();$('#goalForm').onsubmit=async event=>{event.preventDefault();const goalValue=Number(new FormData(event.currentTarget).get('goalValue'));if(!Number.isFinite(goalValue)||goalValue<=0){toast('0보다 큰 목표 금액을 입력하세요.');return}try{await api('/api/settings',{method:'POST',body:JSON.stringify({goalValue})});await load();toast('자산 목표를 저장했습니다.');viewOverrides.today()}catch(error){toast(error.message)}};
  };

  queueMicrotask(()=>{
    viewOverrides.positions=()=>{
      const d=state.data,m=d.metrics;title('Positions','보유 현황과 성과에만 집중합니다');
      const tracking=d.positions.map(position=>{let evidence={};try{evidence=JSON.parse(position.evidence_json||'{}')}catch{}const tags=Object.values(evidence).flat();return `<article class="journal-item"><div style="display:flex;justify-content:space-between;gap:14px;align-items:center"><div><h3>${position.ticker} · 전략 추적</h3><p>${tags.length?tags.join(' · '):'등록된 전략 근거 없음'}</p></div><button class="btn ghost close-position" data-position-id="${position.id}" data-ticker="${position.ticker}" data-price="${position.current_price}">포지션 종료 기록</button></div></article>`}).join('');
      $('#content').innerHTML=`<div class="grid kpis">${kpi('Position value',`$${money(m.positionValue)}`,'Latest recorded closes')}${kpi('Unrealized P&L',`${m.unrealizedPnl>=0?'+':''}$${money(m.unrealizedPnl)}`,'Latest recorded closes',m.unrealizedPnl>=0?'positive':'negative')}${kpi('Portfolio heat',`${m.portfolioHeat.toFixed(1)}%`,'Planned stop risk')}${kpi('Holdings',d.positions.length,'Active positions')}</div><section class="card"><div class="card-head"><div><h2>보유 포지션</h2><p class="sub">온라인 갱신은 각 종목의 최근 완료된 미국장 일봉 종가를 저장합니다.</p></div><div style="display:flex;gap:8px"><button class="btn" id="refreshPositionPrices">온라인에서 가져오기</button><button class="btn secondary" data-go="importPosition">기존 포지션 가져오기</button></div></div>${rows(d.positions)}<p class="sub" style="margin-top:12px">가격 출처: Yahoo Finance 일봉 · 장중 실시간 가격이 아닌 최근 완료된 거래일 종가입니다.</p></section><section class="card" style="margin-top:18px"><div class="card-head"><div><h2>전략 추적</h2><p class="sub">청산 결과는 Analytics의 전략별 성과에 반영됩니다.</p></div></div><div class="journal-list">${tracking||'<div class="empty"><strong>추적 중인 전략이 없습니다.</strong></div>'}</div></section><section class="card" style="margin-top:18px"><div class="card-head"><div><h2>계획 및 시스템 거래</h2><p class="sub">Trade planner에서 생성한 거래</p></div><button class="btn" data-go="planner">새 계획</button></div>${tradesTable([...d.active,...d.planned])}</section>${renderBenchmarks()}`;
      bindGo();$('#refreshPositionPrices').onclick=async event=>{const button=event.currentTarget,original=button.textContent;button.disabled=true;button.textContent='종가를 불러오는 중...';try{const result=await api('/api/positions/refresh-prices',{method:'POST',body:'{}'});await load();const failures=result.results.filter(row=>row.error).map(row=>row.ticker);toast(failures.length?`${result.updated}개 갱신 · 실패: ${failures.join(', ')}`:`${result.updated}개 포지션을 최근 종가로 갱신했습니다.`);viewOverrides.positions()}catch(error){toast(`가격을 불러오지 못했습니다: ${error.message}`);button.disabled=false;button.textContent=original}};document.querySelectorAll('.close-position').forEach(button=>button.onclick=async()=>{const review=await window.InvestmentBetaExit.open({ticker:button.dataset.ticker,defaultPrice:button.dataset.price});if(!review)return;try{await api(`/api/positions/${button.dataset.positionId}`,{method:'PATCH',body:JSON.stringify({status:'closed',...review})});await load();toast('포지션 결과와 매도 근거를 저장했습니다.');viewOverrides.positions()}catch(error){toast(error.message)}});
      $('#benchmarkRun').onclick=async()=>{const output=$('#benchmarkResults'),symbols=$('#benchmarkTickers').value;output.className='empty';output.innerHTML='<strong>시장 데이터를 불러오는 중...</strong>';try{const result=await api(`/api/relative-performance?benchmarks=${encodeURIComponent(symbols)}`);if(!result.comparisons.length){output.innerHTML='<strong>비교할 포지션이 없습니다.</strong>';return}output.className='';output.innerHTML=`<table><thead><tr><th>Position</th><th>Since</th><th>Return</th>${result.benchmarks.map(x=>`<th>${x} / Alpha</th>`).join('')}</tr></thead><tbody>${result.comparisons.map(row=>`<tr><td class="ticker">${row.ticker}</td><td class="mono">${row.openedAt}</td><td class="mono ${row.positionReturnPct>=0?'positive':'negative'}">${row.positionReturnPct>=0?'+':''}${row.positionReturnPct.toFixed(2)}%</td>${row.benchmarks.map(b=>b.error?'<td class="negative">불러오기 실패</td>':`<td class="mono">${b.returnPct>=0?'+':''}${b.returnPct.toFixed(2)}% / <span class="${b.alphaPct>=0?'positive':'negative'}">${b.alphaPct>=0?'+':''}${b.alphaPct.toFixed(2)}%p</span></td>`).join('')}</tr>`).join('')}</tbody></table><p class="sub" style="margin-top:12px">Alpha = 포지션 수익률 − Benchmark 수익률 · Yahoo Finance</p>`}catch(error){output.innerHTML=`<strong>시장 데이터를 불러오지 못했습니다.</strong>${error.message}`}};
    };
  });
}
