export function install({viewOverrides,api}){
  const base=viewOverrides.today;let renderToken=0;
  const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
  const safeUrl=value=>{try{const url=new URL(value);return url.protocol==='https:'?esc(url.href):''}catch{return ''}};
  viewOverrides.today=()=>{base();mount(++renderToken)};
  async function mount(token){
    const host=document.createElement('section');host.className='card macro-card';host.innerHTML='<div class="card-head"><div><h2>US Macro & Event Radar</h2><p class="sub">최신 지표와 앞으로 7일의 변동성 일정을 봅니다.</p></div></div><div class="macro-loading">공식 일정을 불러오는 중…</div>';document.querySelector('#content').appendChild(host);await load(false);
    async function load(force){try{const data=force?await api('/api/macro/refresh',{method:'POST',body:'{}'}):await api('/api/macro');if(token!==renderToken||!host.isConnected||document.body.classList.contains('day-mode'))return;render(data)}catch(error){if(host.isConnected)host.querySelector('.macro-loading').textContent=`불러오지 못했습니다: ${error.message}`}}
    function render(data){const indicators=data.indicators||[],events=nextSevenDays(data.events||[]),today=new Date();host.innerHTML=`<div class="card-head"><div><h2>US Macro & Event Radar</h2><p class="sub">${data.stale?'캐시된 정보 · ':''}발표 시각은 ET와 한국시간(KST)을 함께 표시합니다.</p></div><button class="btn ghost" data-refresh>새로고침</button></div><div class="macro-indicators">${indicators.map((item,index)=>indicator(item,index)).join('')||'<div class="empty">인터넷 연결 후 새로고침해 주세요.</div>'}</div><div class="risk-heading"><div><span>UPCOMING RISK WINDOW</span><h3>오늘부터 향후 7일</h3></div><strong>${events.length} major events</strong></div><div class="seven-day-timeline"><div class="seven-day-line"></div>${dayTicks(today)}<div class="today-pin" title="오늘"><b></b><i></i><span>오늘</span></div>${events.map((event,index)=>eventMarker(event,index)).join('')}</div><p class="source-note">표시 범위 밖 일정은 다음 날 자동으로 이동합니다. 공식 BLS·Federal Reserve 일정과 FRED 관측값을 사용합니다.</p>`;host.querySelector('[data-refresh]').onclick=()=>load(true);host.querySelectorAll('[data-info]').forEach(button=>button.onclick=()=>openInfo(indicators[+button.dataset.info]));host.querySelectorAll('[data-event]').forEach(button=>button.onclick=()=>openEvent(events[+button.dataset.event]))}
  }
  function indicator(item,index){const suffix=item.unit==='%'||item.unit==='YoY'||item.unit==='MoM'?'%':item.unit==='K MoM'?'K':'',direction=['up','down','flat'].includes(item.trendDirection)?item.trendDirection:(+item.delta>0?'up':+item.delta<0?'down':'flat'),count=Math.min(Math.max(Number(item.trendCount)||1,1),2),arrows=direction==='up'?'↑'.repeat(count):direction==='down'?'↓'.repeat(count):'→';return `<article><div><span>${esc(item.title)}</span><div class="macro-value"><strong>${esc(item.value)}${suffix}</strong><em class="trend-${direction}" title="최근 ${count===2?'두 번 연속 ':''}${direction==='up'?'상승':direction==='down'?'하락':'보합'}">${arrows}</em></div><small>${esc(item.date)} · 이전 ${esc(item.previous)}</small></div><button class="info-button" data-info="${index}" aria-label="설명">i</button></article>`}
  function nextSevenDays(events){const start=new Date();start.setHours(0,0,0,0);const end=new Date(start);end.setDate(end.getDate()+8);return events.filter(event=>{const date=new Date(event.startsAt);return date>=start&&date<end}).sort((a,b)=>new Date(a.startsAt)-new Date(b.startsAt))}
  function dayTicks(today){const fmt=new Intl.DateTimeFormat('ko-KR',{month:'numeric',day:'numeric',weekday:'short'});return Array.from({length:8},(_,index)=>{const date=new Date(today);date.setDate(date.getDate()+index);return `<span class="day-tick" style="--pos:${8+index*(84/7)}%">${index===0?`오늘 · ${fmt.format(date)}`:fmt.format(date)}</span>`}).join('')}
  function eventMarker(event,index){const start=new Date();start.setHours(0,0,0,0);const eventDate=new Date(event.startsAt),progress=Math.max(0,Math.min(7,(eventDate-start)/86400000)),position=8+progress*(84/7),lane=index%2;return `<button class="risk-event lane-${lane}" style="--pos:${position}%" data-event="${index}"><i></i><strong>${esc(event.title)}</strong><small>${esc(event.kst)}</small></button>`}
  function openInfo(item){const url=safeUrl(item.sourceUrl);modal(item.title,`<p class="modal-copy">${esc(item.implication)}</p><div class="result-stack"><div class="result-row"><span>이번 발표</span><strong>${esc(item.value)}</strong></div><div class="result-row"><span>이전 발표</span><strong>${esc(item.previous)}</strong></div><div class="result-row"><span>발표일</span><strong>${esc(item.date)}</strong></div></div>${url?`<a class="source-link" href="${url}" target="_blank" rel="noopener noreferrer">공식 출처 열기 ↗</a>`:''}`)}
  function openEvent(event){const url=safeUrl(event.sourceUrl);modal(event.title,`<p class="modal-copy">시장 변동성이 확대될 수 있는 ${esc(event.agency)} 주요 발표입니다.</p><p class="mono">${esc(event.et)}<br>${esc(event.kst)}</p>${url?`<a class="source-link" href="${url}" target="_blank" rel="noopener noreferrer">공식 일정 열기 ↗</a>`:''}`)}
  function modal(title,body){const element=document.createElement('div');element.className='modal-backdrop';element.innerHTML=`<div class="modal-panel compact"><div class="modal-head"><h2>${esc(title)}</h2><button class="btn ghost">닫기</button></div><div class="modal-body">${body}</div></div>`;document.body.appendChild(element);element.querySelector('button').onclick=()=>element.remove()}
}
